#!/bin/bash
VERSION=0.1.0

# Usage:
#   marathon program inputfile [inputfile...]
#   marathon -h
#   marathon -v

function help_page {
  sed -ne '/#[^!]\(.*\)/{
    /\/#/d
    s/    //
    s/# //p
  }' "$0"
}

# Options:
while getopts ":hv" opt "$@"; do
  case $opt in
    h)
      # -h show this help message
      help_page
      exit 0
      ;;
    v)
      # -v show version
      echo "$(basename "$0")" "$VERSION"
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

program=$1
shift $((OPTIND))

# Examples:

function exec_orca {
  : "${ORCABIN:?"ORCABIN must point to your ORCA installation."}"

  inputfile=$1

  #  $ marathon orca {methane,ethane,n-propane}.inp
  inputfile_basename=$(basename "$inputfile" ".inp")
  $ORCABIN "${inputfile_basename}.inp" | tee "${inputfile_basename}.out"
}

for inputfile in "$@"; do
  if [ -r "$inputfile" ]; then
    if [ "$program" = orca ]; then
      exec_orca "$inputfile"
    fi
  else
    echo "  $inputfile does not exist or is not readable."
    exit 1
  fi
done

# Licensed under the MIT License (MIT)
